routes/web.php
<?php

Route::get('/', 'WebSiteController@home')->name('home');

Route::get('/tela', 'WebSiteController@login')->name('login');

Route::get('/post/{slug}', ['as' => 'post.item', 'uses' => 'WebSiteController@post'])->where('slug', '[\w\d\-\_]+');



Route::get('/categoria/financa', 'WebSiteController@financa')->name('financa');

Route::get('/categoria/vender_e_receber', 'WebSiteController@venderereceber')->name('venderereceber');

Route::get('/categoria/na_midia', 'WebSiteController@namidia')->name('namidia');




Route::get('/pagenotfound', 'WebSiteController@pagenotfound')->name('pagenotfound');

Route::group(['prefix' => 'admin', 'middleware' => 'auth:web'], function () {
    Route::get('/', 'HomeController@index')->name('admin.home');

    Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

    Route::resource('post', 'PostController');

    Route::resource('historico', 'HistoricoController');

    Route::resource('usuario', 'UserController');
    Route::get('usuario/{usuario}/editar_senha', 'UserController@editPassword')->name('usuario.editar_senha');
    Route::post('usuario/atualizar_senha/{usuario}', 'UserController@updatePassword')->name('usuario.atualizar_senha');
});

Auth::routes();

resources/views/admin/usuarios/create.blade.php
@extends('admin.main')

@section('page-title')
  Usuários
@endsection

@section('content')
<div class="col-12">
  <div class="card-box">
    <h4 class="m-t-0 header-title"><b>Cadastro de usuários</b></h4>

        {{ Form::open(['route' => 'usuario.store', 'files' => true]) }}
            <div class="row">
                <div class="col-md-6 offset-md-3">
                  {{ Form::label('nome', 'Nome do usuário') }}
                  {{ Form::text('nome', null, array('class' => 'form-control')) }}
                </div>
                <div class="col-md-6 offset-md-3">
                  {{ Form::label('email', 'Email do usuário') }}
                  {{ Form::text('email', null, array('class' => 'form-control')) }}
                </div>
                <div class="col-md-6 offset-md-3">
                  {{ Form::label('nivel', 'Usuário administrador?') }}
                  <br>
                  <p class="p-v-xs">
                      <input name="nivel" type="radio" value="0" id="op1" checked  />
                      <label for="op1">Não</label>
                      <input name="nivel" type="radio" value="1" id="op2" />
                      <label for="op2">Sim</label>
                  </p>
                </div>
                <div class="col-md-6 offset-md-3">
                  {{ Form::label('password', 'Senha') }}
                  {{ Form::password('password', array('class' => 'form-control')) }}
                </div>
                <div class="col-md-6 offset-md-3">
                  {{ Form::label('password_confirmation', 'Confirmar senha:') }}
                  {{ Form::password('password_confirmation', array('class' => 'form-control')) }}
                </div>

                <div class="col-md-6 offset-md-3">
                  {{ Form::label('imagem','Imagem do Usuário') }}
                  <input type="file" name="imagem" class="filestyle" data-buttonText="Carregar" data-btnClass="btn-light" required>
                </div>

            </div>

            <div class="row">
              <div class="col-md-4 offset-md-4" style="margin-top: 15px">
                <div class="col-6 col-md-6" style="float: left">
                  {{ Form::submit('Salvar', array('class' => 'btn btn-success btn-block')) }}
                </div>
                <div class="col-6 col-md-6" style="float: left">
                  {{ Html::linkRoute('usuario.index', 'Cancelar', null, ['class' => 'btn btn-danger btn-block']) }}
                </div>
              </div>
            </div>
        {{ Form::close() }}

  </div>
</div>
@endsection

@section('scripts')
  <script src="{{ asset('template/js/pages/form_elements.js') }}"></script>
  <script src="{{ asset('template/plugins/bootstrap-filestyle/js/bootstrap-filestyle.min.js') }}" type="text/javascript"></script>
@endsection

resources/views/admin/usuarios/edit.blade.php
@extends('admin.main')

@section('page-title')
Editar Usuário
@endsection
@section('page-caminho')
  Usuários
@endsection

@section('content')
<div class="col-12">
  <div class="card-box">
    <h4 class="m-t-0 header-title"><b>Cadastro de usuários</b></h4>

        {{ Form::model($usuario, ['route' => ['usuario.update', $usuario->id], 'method' => 'PUT', 'files' => true]) }}
            <div class="row">
                <div class="col-md-6 offset-md-3">
                  {{ Form::label('nome', 'Nome do usuário') }}
                  {{ Form::text('nome', null, array('class' => 'form-control')) }}
                </div>
                <div class="col-md-6 offset-md-3">
                  {{ Form::label('email', 'Email do usuário') }}
                  {{ Form::text('email', null, array('class' => 'form-control')) }}
                </div>
                <div class="col-md-6 offset-md-3">
                  {{ Form::label('nivel', 'Usuário administrador?') }}
                  <br>
                  <p class="p-v-xs">
                      <input name="nivel" type="radio" value="0" id="op1" {{ ($usuario->nivel == 0) ? 'checked' : '' }}/>
                      <label for="op1">Não</label>
                      <input name="nivel" type="radio" value="1" id="op2" {{ ($usuario->nivel == 1) ? 'checked' : '' }}/>
                      <label for="op2">Sim</label>
                  </p>
                </div>
                <div class="col-md-6 offset-md-3">
                  {{ Form::label('imagem','Imagem do Usuário') }}
                  <input type="file" name="imagem" class="filestyle" data-buttonText="Carregar" data-btnClass="btn-light" required>
                </div>
            </div>
            <div class="row" style="margin-top: 20px">
              <div class="col-12">
                <div class="text-center">
                  <button class="btn btn-success" type="submit" value="Salvar"><i class="fa fa-save m-r-5"></i> Atualizar</button>
                  <a href="{{ route('usuario.index') }}" class="btn btn-danger"><i class="fa fa-window-close m-r-5"></i> Cancelar</a>
                </div>
              </div>
            </div>
        {{ Form::close() }}

  </div>
</div>
@endsection

@section('scripts')
  <script src="{{ asset('template/js/pages/form_elements.js') }}"></script>
@endsection

resources/views/admin/usuarios/edit_password.blade.php
@extends('admin.main')

@section('page-title')
  Usuários
@endsection

@section('content')
<div class="col-12">
  <div class="card-box">
    <h4 class="m-t-0 header-title"><b>Editar senha de {{ $usuario->nome }}</b></h4>

        {{ Form::model($usuario, ['route' => ['usuario.atualizar_senha', $usuario->id], 'method' => 'POST', 'id' => 'sendForm']) }}
            <div class="row">
                <div class="col-md-6 offset-md-3">
                  {{ Form::label('password', 'Nova Senha') }}
                  {{ Form::password('password', ['class' => 'form-control']) }}
                </div>
                <div class="col-md-6 offset-md-3">
                  {{ Form::label('password_confirmation', 'Confirmar Nova Senha') }}
                  {{ Form::password('password_confirmation', ['class' => 'form-control']) }}
                </div>

                <div class="col-md-6 offset-md-3">
                  {{ Form::label('password_user', 'Digite sua senha de usuário, para confirmar alteração') }}
                  {{ Form::password('password_user', ['class' => 'form-control']) }}
                </div>
            </div>
            <div class="row" style="margin-top: 20px">
              <div class="col-12">
                <div class="text-center">
                  <button class="btn btn-success" type="submit" value="Salvar"><i class="fa fa-save m-r-5"></i> Atualizar</button>
                  <a href="{{ route('usuario.index') }}" class="btn btn-danger"><i class="fa fa-window-close m-r-5"></i> Cancelar</a>
                </div>
              </div>
            </div>
        {{ Form::close() }}

  </div>
</div>
@endsection

@section('scripts')
<script src="{{ asset('template/js/pages/form_elements.js') }}"></script>
@endsection

resources/views/admin/usuarios/index.blade.php
@extends('admin.main')

@section('styles')
  <meta name="csrf-token" content="{{ csrf_token() }}">
@endsection

@section('page-title')
  Usuários Cadastrados
@endsection

@section('page-caminho')
  Usuários
@endsection

@section('content')
<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <form method="POST" action="{{ route('usuario.destroy', '1') }}" id='formDestroyer' accept-charset="UTF-8">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="myModalLabel">Exclusão de usuário</h5>
            </div>
            <div class="modal-body">
               <h6>Confirme sua senha de usuário para efetuar a exclusão</h6>
               <div class="row">
                 <div class="col-md-6 offset-md-3">
                   <input type="password" name="senhaUsuarioLogado" class="form-control">
                   <input type="hidden" name="idUsuario" id="idUsuario">
                 </div>
               </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">Cancelar</button>
                {{ csrf_field() }}
                <input name="_method" type="hidden" value="DELETE">
                <button type="submit" class="btn btn-primary waves-effect waves-light" value="Deletar">Confirmar</button>
            </div>
        </div><!-- /.modal-content -->
      </form>
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="col-12">
  <div class="card-box">
    <a href="{{ route('usuario.create') }}" style="margin-bottom: 15px" class="btn btn-info waves-effect waves-light pull-right"><i class="fa fa-plus m-r-5"></i> Adicionar</a>
    <h4 class="m-t-0 header-title">Usuários Cadastrados</h4>

    <table class="table table-striped">
        <thead>
        <tr>
          <th>Nome</th>
          <th>Email</th>
          <th>Ações</th>
        </tr>
        </thead>
        <tbody>
          @forelse($usuarios as $usuario)
            <tr>
              @if($usuario->id != 1)
                <td>{{ $usuario->nome }}</td>
                <td>{{ $usuario->email }}</td>
                <td width="15%">
                    <span class="hint--top" aria-label="Editar usuário"><a href="{{ route('usuario.edit', $usuario->id) }}" style="border-radius: 50%" class="btn btn-warning waves-effect"> <i class="fa fa-pencil m-r-5"></i></a></span>
                    <span class="hint--top" aria-label="Alterar senha"><a href="{{ route('usuario.editar_senha', $usuario->id) }}" style="border-radius: 50%" class="btn btn-secondary waves-effect"> <i class="fa fa-key m-r-5"></i></a></span>
                    <span class="hint--top" aria-label="Deletar usuário"><button type="button" style="border-radius: 50%" onclick="$('#idUsuario').val({{$usuario->id}})" class="btn btn-danger waves-effect" data-toggle="modal" data-target="#myModal"> <i class="fa fa-trash m-r-5"></i></button></span>
                </td>
            </tr>
            @endif
          @empty
            <tr>
                <td colspan="4" class="text-center">Nenhum Item cadastrado</td>
            </tr>
          @endforelse
        </tbody>
    </table>
    @if ($usuarios->lastPage() > 1)
        <ul class="pagination ml-auto">
            <li class="{{ ($usuarios->currentPage() == 1) ? ' disabled' : '' }} page-item">
                <a class=" page-link " href="{{ $usuarios->url(1) }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            @for ($i = 1; $i <= $usuarios->lastPage(); $i++)
                <li class="{{ ($usuarios->currentPage() == $i) ? ' active' : '' }} page-item">
                    <a class=" page-link " href="{{ $usuarios->url($i) }}">{{ $i }}</a>
                </li>
            @endfor
            <li class="{{ ($usuarios->currentPage() == $usuarios->lastPage()) ? ' disabled' : '' }} page-item">
                <a href="{{ $usuarios->url($usuarios->currentPage()+1) }}" class="page-link" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>
    @endif  </div>

</div>

@endsection

@section('scripts')

  <script>

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

  </script>

@endsection