routes/web.php
<?php

Route::get('/', 'WebSiteController@home')->name('home');

Route::get('/tela', 'WebSiteController@login')->name('login');

Route::get('/post/{slug}', ['as' => 'post.item', 'uses' => 'WebSiteController@post'])->where('slug', '[\w\d\-\_]+');



Route::get('/categoria/financa', 'WebSiteController@financa')->name('financa');

Route::get('/categoria/vender_e_receber', 'WebSiteController@venderereceber')->name('venderereceber');

Route::get('/categoria/na_midia', 'WebSiteController@namidia')->name('namidia');




Route::get('/pagenotfound', 'WebSiteController@pagenotfound')->name('pagenotfound');

Route::group(['prefix' => 'admin', 'middleware' => 'auth:web'], function () {
    Route::get('/', 'HomeController@index')->name('admin.home');

    Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

    Route::resource('post', 'PostController');

    Route::resource('historico', 'HistoricoController');

    Route::resource('usuario', 'UserController');
    Route::get('usuario/{usuario}/editar_senha', 'UserController@editPassword')->name('usuario.editar_senha');
    Route::post('usuario/atualizar_senha/{usuario}', 'UserController@updatePassword')->name('usuario.atualizar_senha');
});

Auth::routes();

resources/views/admin/partials/_aside.blade.php
<div class="left side-menu">
    <div class="slimscroll-menu" id="remove-scroll">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu" id="side-menu">
                <li class="menu-title">Menu</li>

                <li>
                  <a href="{{ route('post.index') }}">
                    <i class="mdi mdi-note-text"></i> <span> PJA Blog </span>
                  </a>
                </li>

              <!-- @if(Auth::User()->nivel == 1)
                  <li>
                      <a href="{{ route('historico.index') }}">
                          <i class="dripicons-document"></i> <span> Histórico de Atividades </span>
                      </a>
                  </li>
                  <li>
                      <a href="{{ route('usuario.index') }}">
                          <i class="fa fa-user"></i> <span> Usuários </span>
                      </a>
                  </li>
                @endif
            </ul> -->

        </div>
        <!-- Sidebar -->
        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>

resources/views/admin/partials/_bottom.blade.php
<!-- jQuery  -->
<script src="{{ asset('template/js/jquery.min.js') }}"></script>
<script src="{{ asset('template/js/popper.min.js') }}"></script>
<script src="{{ asset('template/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('template/js/metisMenu.min.js') }}"></script>
<script src="{{ asset('template/js/waves.js') }}"></script>
<script src="{{ asset('template/js/jquery.slimscroll.js') }}"></script>
<script src="{{ asset('template/plugins/waypoints/lib/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('template/plugins/counterup/jquery.counterup.min.js') }}"></script>

<!-- Chart JS -->
<script src="{{ asset('template/plugins/chart.js/chart.bundle.js') }}"></script>

<!-- init dashboard -->
<script src="{{ asset('template/pages/jquery.dashboard.init.js') }}"></script>

<!-- responsive-table-->
<script src="{{ asset('template/plugins/responsive-table/js/rwd-table.min.js') }}" type="text/javascript"></script>

<!-- App js -->
<script src="{{ asset('template/js/jquery.core.js') }}"></script>
<script src="{{ asset('template/js/jquery.app.js') }}"></script>

<script src="{{ asset('template/js/jquery.mask.min.js') }}"></script>

<script src="{{ asset('template/plugins/sweet-alert/sweetalert2.min.js') }}"></script>
<script src="{{ asset('template/pages/jquery.sweet-alert.init.js') }}"></script>

@yield('script-bottom')

resources/views/admin/partials/_head.blade.php
<head>
    <meta charset="utf-8" />
    <title>Painel Administrativo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">


    <!-- App favicon -->
    <link rel="shortcut icon" href="{{ asset('theme/images/favicon.png') }}">

    <!-- App css -->
    <link href="{{ asset('template/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('template/css/icons.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('template/css/metismenu.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('template/css/style.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/estilo.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/dropzone.css') }}" rel="stylesheet" type="text/css" />


    <!-- Hint css -->
    <link href="{{ asset('css/hint.min.css') }}" rel="stylesheet" type="text/css" />

    <script src="{{ asset('template/js/modernizr.min.js') }}"></script>
</head>

resources/views/admin/partials/_message.blade.php
@if(Session::has('success'))
  <div class="alert alert-success alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong></strong> {{ Session::get('success') }}
  </div>
@endif

@if(count($errors)>0)
  <div class="alert alert-danger alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Errors</strong>
    <ul>
      @foreach($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>

@endif

resources/views/admin/partials/_nav.blade.php
<nav class="navbar-custom">

    <ul class="list-unstyled topbar-right-menu float-right mb-0">

        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="false" aria-expanded="false">
                <span class="ml-1">{{ Auth::User()->nome }}<i class="mdi mdi-chevron-down"></i> </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                <!-- item-->
                <div class="dropdown-item noti-title">
                    <h6 class="text-overflow m-0">Usuário</h6>
                </div>

                <!-- item-->
                <a href="{{ route('logout') }}" class="dropdown-item notify-item" onclick="event.preventDefault();
                       document.getElementById('logout-form').submit();">
                    <i class="fi-power"></i> <span>Sair</span>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </a>

            </div>
        </li>

    </ul>

    <ul class="list-inline menu-left mb-0">
        <li class="float-left">
            <button class="button-menu-mobile open-left waves-light waves-effect">
                <i class="dripicons-menu"></i>
            </button>
        </li>
    </ul>

</nav>